### ISSUE TITLE
Is 0.5.0 coming any soon?

### ISSUE THREAD

**Issue by erolm-a** [lightcopy/parquet-index#101]
I think that the latest 2 PRs are quite major changes (support for Spark 3.0 and deprecation of python 2 api), so it would be a good idea to annotate the master branch with a new tag.

Unless you plan to tackle other issues first :)

**Comment by sadikovi** [comment]
Good point. I will try doing it this weekend 😄

**Comment by sadikovi** [comment]
Done.
