### ISSUE TITLE
Is there support for spark 2.1 or 2.2 in the roadmap?

### ISSUE THREAD

**Issue by sbilello** [lightcopy/parquet-index#78]

**Comment by sadikovi** [comment]
Hi. To be honest, I have not thought about updating to Spark 2.1/2.2, the main motivation being Spark 2.1+ with faster file listing and pruning, but I might be wrong.

I am a bit snowed under currently with other work, so I will try getting to this during holidays or January. Meanwhile, any help would be greatly appreciated!
