### ISSUE TITLE
Check if project still works on Spark 2.3 and Spark 2.4

### ISSUE THREAD

**Issue by sadikovi** [lightcopy/parquet-index#90]
We stopped maintaining it properly since Spark 2.2. We should verify and run tests for Spark 2.3 and Spark 2.4 and make a release.

**Comment by Aaaaaaron** [comment]
+1

**Comment by sadikovi** [comment]
For Spark 2.3.x build project for commit [fd442d](https://github.com/lightcopy/parquet-index/commit/fd442d2b555d89802d3c404d26ad0444f1016b3e).

For Spark 2.4.x either build master or [5051f9](https://github.com/lightcopy/parquet-index/commit/5051f9682b385b636795b67c264cb83b83c23004)
